message_inbox:
    path:     /
    defaults: { _controller: MessageBundle:Message:inbox }

message_sent:
    path:     /sent
    defaults: { _controller: MessageBundle:Message:sent }

message_deleted:
    path:     /deleted
    defaults: { _controller: MessageBundle:Message:deleted }

message_search:
    path:     /search
    defaults: { _controller: MessageBundle:Message:search }

message_newThread:
    path:     /new
    defaults: { _controller: MessageBundle:Message:newThread }

message_delete:
    path:     /{threadId}/delete
    defaults: { _controller: MessageBundle:Message:delete }
    methods:  [POST, DELETE]

message_undelete:
    path:     /{threadId}/undelete
    defaults: { _controller: MessageBundle:Message:undelete }
    methods:  [POST]

message_thread_view:
    path:     /{threadId}
    defaults: { _controller: MessageBundle:Message:thread }