shoutbox_get:
    path:     /shoutbox/{lastId}/{rand}
    defaults: { _controller: ShoutboxBundle:Shoutbox:getShoutbox }

shoutbox_send:
    path:     /sendshout
    defaults: { _controller: ShoutboxBundle:Shoutbox:sendShoutbox }

shoutbox_del:
    path:     /delshout
    defaults: { _controller: ShoutboxBundle:Shoutbox:delShoutbox}