<?php

namespace Shoutbox\ShoutboxBundle\Repository;

/**
 * shoutboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class shoutboxRepository extends \Doctrine\ORM\EntityRepository
{
}
