<?php

namespace Users\UsersBundle\Repository;

/**
 * InfosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfosUserRepository extends \Doctrine\ORM\EntityRepository
{
}
