<?php

namespace Users\UsersBundle\Repository;

/**
 * MoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
