<?php

namespace Users\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * MoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoodsRepository extends EntityRepository
{
    public function getMoodsList()
    {
        $qb = $this->createQueryBuilder('m');
        return $qb->getQuery()->getResult(Query::HYDRATE_ARRAY);
    }
}
