<?php

namespace Users\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    public function findUserIdByUsername($usr)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT u.id FROM UsersBundle:Users u WHERE u.username = :username'
            )
            ->setParameter('username', $usr)
            ->getResult();
    }
}
