<?php

namespace Forums\ForumsBundle\Repository;

/**
 * ForumsCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
