<?php

namespace Forums\ForumsBundle\Repository;

/**
 * ForumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsRepository extends \Doctrine\ORM\EntityRepository
{
}
