<?php

namespace Forums\ForumsBundle\Repository;

/**
 * ForumsReadPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsReadPostsRepository extends \Doctrine\ORM\EntityRepository
{
}
