<?php

namespace Forums\ForumsBundle\Repository;

/**
 * ForumsPostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsPostsRepository extends \Doctrine\ORM\EntityRepository
{
}
