<?php

namespace Forums\ForumsBundle\Repository;

/**
 * ForumsTopicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumsTopicsRepository extends \Doctrine\ORM\EntityRepository
{
}
