imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@CMSBundle/Resources/config/services.yml" }
    - { resource: "@UsersBundle/Resources/config/services.yml" }
    - { resource: "@InformationsBundle/Resources/config/services.yml" }
    - { resource: "@MessageBundle/Resources/config/services.yml" }
    - { resource: "@ShoutboxBundle/Resources/config/services.yml" }
    - { resource: "@ForumsBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi:             ~
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_name: '%site_name%'
        site_url: '%site_url%/web/app_dev.php'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: '5.5'
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        #metadata_cache_driver: apc
        #query_cache_driver: apc

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    encryption: "%mailer_encryption%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~
    bundles: [CMSBundle]

# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Users\UsersBundle\Entity\Users
    registration:
        form:
            type: Users\UsersBundle\Form\RegistrationType
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

fos_message:
    db_driver: orm
    thread_class: Users\UsersBundle\Entity\Thread
    message_class: Users\UsersBundle\Entity\Message
    #message_manager:        fos_message.message_manager         # See ModelManager\MessageManagerInterface
    #thread_manager:         fos_message.thread_manager          # See ModelManager\ThreadManagerInterface
    #sender:                 fos_message.sender                  # See Sender\SenderInterface
    #composer:               fos_message.composer                # See Composer\ComposerInterface
    #provider:               fos_message.provider                # See Provider\ProviderInterface
    #participant_provider:   fos_message.participant_provider    # See Security\ParticipantProviderInterface
    #authorizer:             fos_message.authorizer              # See Security\AuthorizerInterface
    #message_reader:         fos_message.message_reader          # See Reader\ReaderInterface
    #thread_reader:          fos_message.thread_reader           # See Reader\ReaderInterface
    #deleter:                fos_message.deleter                 # See Deleter\DeleterInterface
    spam_detector:          fos_message.noop_spam_detector      # See SpamDetection\SpamDetectorInterface
    #twig_extension:         fos_message.twig_extension          # See Twig\Extension\MessageExtension
    #user_transformer:       fos_user.user_transformer           # See Symfony\Component\Form\DataTransformerInterface
    search:
        #finder:             fos_message.search_finder           # See Finder\FinderInterface
        #query_factory:      fos_message.search_query_factory    # See Finder\QueryFactoryInterface
        query_parameter:    'q'                                     # Request query parameter containing the term
    new_thread_form:
        #factory:            fos_message.new_thread_form.factory # See FormFactory\NewThreadMessageFormFactory
        type:               FOS\MessageBundle\FormType\NewThreadMessageFormType
        #handler:            fos_message.new_thread_form.handler # See FormHandler\NewThreadMessageFormHandler
        name:               message
    reply_form:
        #factory:            fos_message.reply_form.factory      # See FormFactory\ReplyMessageFormFactory
        type:               FOS\MessageBundle\FormType\ReplyMessageFormType
        #handler:            fos_message.reply_form.handler      # See FormHandler\ReplyMessageFormHandler
        name:               message