torrents:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix:   /

informations:
    resource: "@InformationsBundle/Resources/config/routing.yml"
    prefix:   /

utilisateurs:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /mailbox