<?php

namespace Informations\InformationsBundle\Repository;

/**
 * AdvertisementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertisementsRepository extends \Doctrine\ORM\EntityRepository
{
}
